### ISSUE TITLE
Improve parsing of diacritics

### ISSUE THREAD

**Issue by Zasco** [noah-severyn/SC4PackMan#47]
Currently, characters with diacritics are removed in the parsing of the **[EntryValidation()](https://github.com/noah-severyn/SC4PackMan/blob/main/wwwroot/js/site-interactivity.js#L68)** function. The expected behavior would be to remove the diacritic and keep the base character.

**Comment by noah-severyn** [comment]
Perhaps something like [this](https://stackoverflow.com/a/46192691/10802255)?

**Comment by Zasco** [comment]
> Perhaps something like [this](https://stackoverflow.com/a/46192691/10802255)?

Yep. It happened to me when trying to write the metadata for _koumus_' [_Lidingö Källängsvägen_](https://community.simtropolis.com/files/file/34103-liding%C3%B6-k%C3%A4ll%C3%A4ngsv%C3%A4gen/). The "_o_" and "_a_"s were completly removed and I was left with "_liding-kllngsvgen_".
