### ISSUE TITLE
Import data from existing YAML file

### ISSUE THREAD

**Issue by noah-severyn** [noah-severyn/SC4PackMan#50]
Point to a YAML file on the default (or a custom) channel and import the YAML data into the editor for easier updating of metadata.

**Comment by Zasco** [comment]
Isn't this kind of a subtask of #31?

**Comment by noah-severyn** [comment]
Kind of, but import the file from an online host instead of the local filesystem.

**Comment by Zasco** [comment]
I think they should be merged, as **#31** didn't imply the local filesystem... Unless you think it's better the current way as it allows to complete the issues, and the features, independently.

**Comment by noah-severyn** [comment]
Eh, fair enough. I'll just keep this open as a reminder and both can be closed at the same time.
